### ISSUE TITLE
Objetive tris code???

### ISSUE THREAD

**Issue by DanielSarmiento04** [jssdvv/AFI-VBA#1]
What Is the meaning of this code ?

**Comment by jssdvv** [comment]
The stereotype of utils, but for my Excel macros

**Comment by DanielSarmiento04** [comment]
Ohhhhh x), goood

**Comment by DanielSarmiento04** [comment]
What kind of data do you save?

**Comment by jssdvv** [comment]
One of my 10 macros for now, but just the code not the file
